### ISSUE TITLE
How to run clusters on different hosts

### ISSUE THREAD

**Issue by richenlin** [blacktop/docker-elasticsearch-alpine#1]
The document provides a cluster running on the same host, but does not support different host clusters,
Will you be able to provide the configuration, for example:

docker run -d  -e "cluster.name=ES" -e "node.name=Node_ES1" -e "network.host=192.168.0.1" -e "network.publish_host=192.168.0.1" -e "discovery.zen.minimum_master_nodes=3" -e "discovery.zen.ping.unicast.hosts=[\"192.168.0.2:9300\", \"192.168.0.3:9300\", \"192.168.0.4:9300\"]" ......

**Comment by blacktop** [comment]
So the official elasticsearch docker image works that way.  You can see here that they parse the env vars and format them as input args to elasticsearch - https://github.com/elastic/elasticsearch-docker/blob/master/build/elasticsearch/bin/es-docker

I will add something like that eventually, but the official image pretty much has the best of what I am doing and what the **old** official image was doing.

Thank you for using my image, but I think it will be something I use for *me* as the official image is so good now.

**Comment by blacktop** [comment]
ummmmm I guess you can do this too, I don't read my own docs haha - https://github.com/blacktop/docker-elasticsearch-alpine/blob/master/docs/production.md

**Comment by blacktop** [comment]
```bash
$ docker run -d blacktop/elasticsearch -Ecluster.name=ES -Enode.name=Node_ES1 -Enetwork.host=192.168.0.1 -Enetwork.publish_host=192.168.0.1 -Ediscovery.zen.minimum_master_nodes=3 -Ediscovery.zen.ping.unicast.hosts=["192.168.0.2:9300", "192.168.0.3:9300", "192.168.0.4:9300"
```
