### ISSUE TITLE
Version 7 images are significantly larger than images for versions 5 and 6

### ISSUE THREAD

**Issue by dpursehouse** [blacktop/docker-elasticsearch-alpine#10]
Compared to the official images, the blacktop images for versions 5 and 6 are a lot smaller.

For 5.6.16 it's ~400MB smaller:
```
$ docker image ls | grep 5.6.16
blacktop/elasticsearch                              5.6.16                 121MB
docker.elastic.co/elasticsearch/elasticsearch       5.6.16                 529MB
```

For 6.5.4 it's ~500MB smaller:
```
$ docker image ls | grep 6.5.4
blacktop/elasticsearch                              6.5.4                  121MB
docker.elastic.co/elasticsearch/elasticsearch-oss   6.5.4                  645MB
```

But for 7.2.0 the blacktop image is ~500MB larger than the other versions, and is not a lot smaller than the official image:
```
$ docker image ls | grep 7.2.0
blacktop/elasticsearch                              7.2.0                  625MB
docker.elastic.co/elasticsearch/elasticsearch-oss   7.2.0                  768MB
```

Is there anything that can be done to reduce the size?

**Comment by blacktop** [comment]
Hmmmm it looks like they are now including the JDK with the install tar file?  So I suppose I could either skip installing it in alpine or rm it from the tar to get back the size I gained?

**Comment by blacktop** [comment]
So removing the included JDK got it down to **358MB** 😁

**Comment by dpursehouse** [comment]
I'm not sure why they're including the JDK.  I wonder if that's intentional?

Anyway, thanks for looking into this and finding the cause.  I see you've fixed it for 7.2, but would you be able to do the same for 7.0 and 7.1 which are also quite large?

**Comment by blacktop** [comment]
done 👍

**Comment by dpursehouse** [comment]
Thanks.  I've just pulled the 7.2.0 image again and it's a lot smaller.  Still almost 200MB larger than the 6.7.2 image though...
