### ISSUE TITLE
Add ARM support

### ISSUE THREAD

**Issue by un1r8okq** [blacktop/docker-elasticsearch-alpine#14]
People with common home servers like [ODroids](https://www.hardkernel.com/shop/odroid-hc2-home-cloud-two/) or [Raspberry Pis](https://www.raspberrypi.org/products/raspberry-pi-3-model-b-plus/) who are wanting to run Dockerised Elasticsearch on an [ARM CPU](https://en.wikipedia.org/wiki/ARM_architecture) currently have to try hack together something of my own and can't use this image.  [The build artifacts on their download page should support ARM already](https://discuss.elastic.co/t/compiling-elasticsearch-for-arm/145553/3), so this shouldn't be much work.

**Comment by karlhendrik** [comment]
> People with common home servers like [ODroids](https://www.hardkernel.com/shop/odroid-hc2-home-cloud-two/) or [Raspberry Pis](https://www.raspberrypi.org/products/raspberry-pi-3-model-b-plus/) who are wanting to run Dockerised Elasticsearch on an [ARM CPU](https://en.wikipedia.org/wiki/ARM_architecture) currently have to try hack together something of my own and can't use this image. [The build artifacts on their download page should support ARM already](https://discuss.elastic.co/t/compiling-elasticsearch-for-arm/145553/3), so this shouldn't be much work.

Agreed with @WillMoreland, tried running official dockerfiles offered by elastic but it uses centos as base image and when trying to build image on RPi4 networking fails and there is no easy workaroud. Even tried to build image on my Macbook with experimental features like "docker buildx", but still nothing. I hope ARM gets better support in near future.

**Comment by ezpuzz** [comment]
@karlhendrik thansk for that command!

I just was able to build 6.8 for linux/arm64 and run on my M1 macbook without a problem so far.  Could not find any other working docker image to run on M1 before this.

**Comment by danielvega2** [comment]
@ezpuzz may I know the full process u did on the M1 mac? I'm facing the same problem, can't get it to work

**Comment by convenient** [comment]
1. Replace `yournamespace` with your namespace.
1. `cd` into https://github.com/blacktop/docker-elasticsearch-alpine/tree/master/6.5 for example

```
cd ../6.5.4
docker buildx create --name mybuilder --use
docker buildx build -t yournamespace/elasticsearch:6.5.4 --platform linux/amd64,linux/arm64 --push . 
docker buildx stop mybuilder
docker buildx rm mybuilder
```

Got this building `linux/amd64` and `linux/arm64` without issue
