### ISSUE TITLE
7.3 image is unusable

### ISSUE THREAD

**Issue by Jerska** [blacktop/docker-elasticsearch-alpine#18]
Hey @blacktop ,

First, thanks for this image that has been incredibly useful for me and my team, without burning our machines with an image too big for what it does.

It seems like something went wrong for the build of the `7.3` image.
The image is only 5MB and trying to run it fails with:
```sh
standard_init_linux.go:211: exec user process caused "no such file or directory"
```

```sh
$ docker images                                                                                                                                                                                               
REPOSITORY               TAG     IMAGE ID      CREATED        SIZE
blacktop/elasticsearch   7.3     fc3e1dbdffa9  3 hours ago    5.59MB
```

**Comment by blacktop** [comment]
Thank you for pointing that out to me, I'm not sure what happened?  DockerHUB says it built correctly?  I am rebuilding in DockerHUB now.

**Comment by blacktop** [comment]
So I rebuilt and it was the same, this was because it was using Build Cache, so the cache got corrupted somehow, disabling the cache has fixed the issue.  Thank you for letting me know.

**Comment by Jerska** [comment]
Thank you for your quick response and fix!
All good now it seems. :)
