### ISSUE TITLE
ElasticSearch x-pack-7.6.1 based on Debian and not on Alpine Linux as expected

### ISSUE THREAD

**Issue by binlab** [blacktop/docker-elasticsearch-alpine#29]
Hi @blacktop!
Looks like image `blacktop/elasticsearch:x-pack-7.6.1` based not on `Alpine Linux` as I expected but on Debian. Here the proof:
https://github.com/blacktop/docker-elasticsearch-alpine/blob/90c412f28a90aa7c8b34a516ecf0f2d51399b317/x-pack/Dockerfile#L1
strange.. do you have plans to move it on `Alpine Linux`?
Thanks!

**Comment by blacktop** [comment]
So I am not sure if this is still the case, but a while back I was not able to get any of the ML stuff to work in alpine so I make the X-Pack image debian based so that people could use all those cool machine learning features.  Do you know if that is still the case?
