### ISSUE TITLE
Change default credentials on startup

### ISSUE THREAD

**Issue by uLan08** [blacktop/docker-elasticsearch-alpine#3]
Is there a way to change the default credentials during startup? For example in the official postgres image I could change the default credentials by passing environment variables, e.g. `POSTGRES_USER` and `POSTGRES_PASSWORD`. Great work on this image btw.

**Comment by blacktop** [comment]
Issue #1 kind of explains how you would do that

I assume you mean the x-pack enabled image?

**Comment by blacktop** [comment]
I have that ability in my elk image here - https://github.com/blacktop/docker-elastic-stack/blob/master/docs/change-pass.md

It looks like elasticsearch is changing the way they deal with passwords in x-pack via a new command:

```

**Comment by blacktop** [comment]
however, usually you would have elastic only accessible from a private network and would hit it from your app using it as the db backend or via kibana with a x-pack password or nginx in front of it.

**Comment by uLan08** [comment]
I don't think I am using the x-pack enabled image since this has the `latest` tag.

**Comment by blacktop** [comment]
Using `ELASTIC_PASSWORD` now works with the `x-pack` images
