### ISSUE TITLE
asCompatibleSubstituteFor("docker.elastic.co/elasticsearch/elasticsearch") required in application code

### ISSUE THREAD

**Issue by marco-miller** [blacktop/docker-elasticsearch-alpine#39]
Based on my explanations in [1]'s commit message below,
the code as per Title here is now required -as in [2]:

[1] https://gerrit-review.googlesource.com/c/gerrit/+/287983
[2] https://gerrit-review.googlesource.com/c/gerrit/+/287983/3/javatests/com/google/gerrit/elasticsearch/ElasticContainer.java

So without this change, such simple application code fails -this way:

```
(...) org.junit.AssumptionViolatedException: Unable to start container
(...) Caused by: java.lang.IllegalStateException:
Failed to verify that image 'blacktop/elasticsearch:6.8.9' is a
compatible substitute for 'docker.elastic.co/elasticsearch/elasticsearch'.

This generally means that you are trying to use an image that
Testcontainers has not been designed to use. If this is deliberate, and
if you are confident that the image is compatible, you should declare
compatibility in code using the `asCompatibleSubstituteFor` method.

For example: DockerImageName myImage =
DockerImageName.parse("blacktop/elasticsearch:6.8.9")
.asCompatibleSubstituteFor("docker.elastic.co/elasticsearch/elasticsearch");
and then use `myImage` instead.
```

**Comment by davido** [comment]
Thanks for following up on that.

**Comment by blacktop** [comment]
@marco-miller does this require any changes to this repo?

**Comment by marco-miller** [comment]
- Not anymore AFAIK, also as ES support is being removed from Gerrit core per se.
- @davido is welcome to comment further if need be; closing until (unless) further notice then.
