### ISSUE TITLE
Tag docker images with the full-semver version of ES

### ISSUE THREAD

**Issue by mikn** [blacktop/docker-elasticsearch-alpine#4]
Hi! Thanks for these excellent images of ES et al! We are using your images as a base for building our own that we include some plugins in. Sadly, you only tag with major/minor version of the ES version and do not include the fix version on the docker image tags. This causes us problems as plugins must be compatible with the full three digit version number. (so a plugin that is registered to work with 6.0.0 will not work with 6.0.1).
Do you think it is possible to tag your images with the full version (i.e 6.0.0 instead of 6.0?)
That would be sweet. :)

**Comment by blacktop** [comment]
I'll do both, hopefully that last commit will help you out 😉 

Thank you for using my images.

**Comment by mikn** [comment]
Woot! Turnaround time! Think you can do the same with your Kibana repository? :)
```Plugin installation was unsuccessful due to error "Incorrect Kibana version in plugin [searchguard]. Expected [6.0.1]; found [6.0.0]"
```

**Comment by blacktop** [comment]
Ask.... and.... you.... shall..... RECIEVE!!!!! 🙏

**Comment by mikn** [comment]
:pray:

**Comment by mikn** [comment]
Can you tag up 6.0.0!?

**Comment by mikn** [comment]
\o/

**Comment by blacktop** [comment]
added, the image should now tag things as `6.0.1, 6.0. 6` on updates from now on.  I won't be back filling though (other than the 6.0.0 exception) 😉
