### ISSUE TITLE
Upgrade images to Alpine 3.13

### ISSUE THREAD

**Issue by MarttiR** [blacktop/docker-elasticsearch-alpine#40]
Alpine versions prior to version 3.13 use HTTP URLs in `/etc/apk/repositories`. This makes the images vulnerable to simple DNS hijacking attacks and prevents using them in environments which do not allow plain HTTP connections.

Would it be possible to upgrade these images to use Alpine 3.13?

[Original issue at docker-alpine repo](https://github.com/alpinelinux/docker-alpine/issues/132)

**Comment by blacktop** [comment]
bumped the latest to 3.13
