### ISSUE TITLE
not find elasticsearch-users

### ISSUE THREAD

**Issue by LiangquanLi930** [blacktop/docker-elasticsearch-alpine#42]
hello, when i run elasticsearch-alpine:6.8 , i can't find elasticsearch-users, maybe i need install elasticsearch-users? thank you very much

**Comment by bodo-hugo-barwich** [comment]
Effectively the `bin/elasticsearch-users` which is documented at [`elasticsearch-users` command documentation](https://www.elastic.co/guide/en/elasticsearch/reference/6.8/users-command.html#users-command) is not included in the package which is installed in the image.
```
$ tar -tzf elasticsearch-oss-6.8.13.tar.gz|grep -i "/bin/"
elasticsearch-6.8.13/bin/
elasticsearch-6.8.13/bin/elasticsearch-env
elasticsearch-6.8.13/bin/elasticsearch-service-x64.exe
elasticsearch-6.8.13/bin/elasticsearch-keystore
elasticsearch-6.8.13/bin/elasticsearch-keystore.bat
elasticsearch-6.8.13/bin/elasticsearch-plugin
elasticsearch-6.8.13/bin/elasticsearch-shard
elasticsearch-6.8.13/bin/elasticsearch.bat
elasticsearch-6.8.13/bin/elasticsearch-shard.bat
elasticsearch-6.8.13/bin/elasticsearch-translog.bat
elasticsearch-6.8.13/bin/elasticsearch-env.bat
elasticsearch-6.8.13/bin/elasticsearch-translog
elasticsearch-6.8.13/bin/elasticsearch-cli
elasticsearch-6.8.13/bin/elasticsearch
elasticsearch-6.8.13/bin/elasticsearch-service.bat
elasticsearch-6.8.13/bin/elasticsearch-cli.bat
elasticsearch-6.8.13/bin/elasticsearch-plugin.bat
elasticsearch-6.8.13/bin/elasticsearch-service-mgr.exe
```
in the documentation the `elasticsearch-users` command is marked as "_x-pack_" feature which means that it requires subscription.
On the other hand this image is based on the **Apache 2.0 Licensed** version as documented in the installation section [Installation from _Tarball_ Package](https://www.elastic.co/guide/en/elasticsearch/reference/6.8/zip-targz.html#install-targz)

> Alternatively, you can download the following package, which includes only Apache 2.0 licensed code: https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-oss-6.8.23.tar.gz

**Comment by blacktop** [comment]
https://github.com/blacktop/docker-elasticsearch-alpine/blob/master/6.8/Dockerfile#L9. I believe that is what I am using?

**Comment by blacktop** [comment]
closing because @bodo-hugo-barwich answered.
