### ISSUE TITLE
Elasticsearch 7.16.2

### ISSUE THREAD

**Issue by stakach** [blacktop/docker-elasticsearch-alpine#43]
Hi, firstly thank you for managing these docker images, we find them immensely useful.
I was wondering when an image for 7.16.2 might be available?

7.16.2 contains the log4j fixes (not that the recent issues effect elasticsearch) and we are being hit with quite a few false positives from vulnerability scanners picking up the package.

Thanks again :)

**Comment by blacktop** [comment]
Thank you for letting me know! 👍

**Comment by blacktop** [comment]
Updated the 6.8.x image as well.
